"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['test-integration.py']
DATA_FILES = []
OPTIONS = {
	'argv_emulation': True,
	'includes': 'pygtk, gtk, glib, cairo, pango, pangocairo, atk, gobject, gio, gtk.keysyms',
	'plist': {
		'CFBundleURLTypes': [{
			'CFBundleURLName': 'gtk-osx',
			'CFBundleURLSchemes': ['gtk-osx'],
		}],
	},
}


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
